/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
 * Generated on: 14-Jun-2023 16:52:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 51
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * H:\matlab2019\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 51;
const real32_T B[51] = {
  -0.0009190982091, -0.00271769613,-0.002486952813, 0.003661438357,   0.0136509249,
    0.01735116541,  0.00766530633,-0.006554719061,-0.007696784101, 0.006105459295,
    0.01387391612,0.0003508617228, -0.01690892503,-0.008905642666,  0.01744112931,
    0.02074504457,  -0.0122964941, -0.03424086422,-0.001034529647,  0.04779030383,
    0.02736303769, -0.05937951803, -0.08230702579,  0.06718690693,   0.3100151718,
     0.4300478697,   0.3100151718,  0.06718690693, -0.08230702579, -0.05937951803,
    0.02736303769,  0.04779030383,-0.001034529647, -0.03424086422,  -0.0122964941,
    0.02074504457,  0.01744112931,-0.008905642666, -0.01690892503,0.0003508617228,
    0.01387391612, 0.006105459295,-0.007696784101,-0.006554719061,  0.00766530633,
    0.01735116541,   0.0136509249, 0.003661438357,-0.002486952813, -0.00271769613,
  -0.0009190982091
};
